# Generated by Django 4.1.7 on 2023-03-28 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_add_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 28, 12, 30, 34, 734257, tzinfo=datetime.timezone.utc)),
        ),
    ]
